#!/bin/bash

DATETIME=`date -u +'%Y%m%dT%H%M%SZ'`

# Defaults
DEVICE=/dev/ttyHSL2
RATE=115200
CONFIGURE=1

show_help() {
    echo
    echo "Usage: capture [-d DEVICE] [-r RATE] [-n] [DIRECTORY]"
    echo 
    echo "    DIRECTORY    Path to save the output file. Defaults to the current directory."
    echo "    -d DEVICE    Specify the device path. Defaults to /dev/ttyHSL2."
    echo "                 On OS X with a USB connection, should be /dev/cu.usbmodem*"
    echo "    -r RATE      Specify the baud rate. Should be 9600 or 115200."
    echo "                 Defaults to 115200."
    echo "    -n           Do not configure the ublox."
    echo 
}

OPTIND=1         # Reset in case getopts has been used previously in the shell.

while getopts "nh?d:r:" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    n)
        CONFIGURE=0
        ;;
    d)  DEVICE=$OPTARG
        ;;
    r)  
        RATE=$OPTARG
        ;;
    esac
done
shift $(($OPTIND - 1))

if [ ! -e $DEVICE ]; then
    echo 
    echo "*** ${DEVICE} does not exist!"
    echo 
    exit 0
fi

if [ ! -c $DEVICE ]; then
    echo 
    echo "*** ${DEVICE} is not a character device!"
    echo 
    exit 0
fi

case "$RATE" in
    9600) ;;
    115200) ;;
    *) 
        echo 
        echo "*** Invalid baud rate!"
        show_help
        exit 0
        ;;
esac

if [ $# -eq 0 ]; then
    OUTPUT_PATH=.
else
    OUTPUT_PATH=$1
fi

if [ $CONFIGURE == 1 ]; then
    ./configure -d $DEVICE -r $RATE
fi

stty -F $DEVICE $RATE

./stream.py --device $DEVICE -o ${OUTPUT_PATH}/ublox_${DATETIME}.ubx